[workspace]

members = [
    "client",
    "server",
    "transport",
    "cli",
    "server/bench"
]

[patch.crates-io]
arrow2 = { git = "https://github.com/WallarooLabs/arrow2", branch = "fmurphy/public-arrow-parquet-schema" }
parquet2 = { git = "https://github.com/WallarooLabs/parquet2", branch = "more-writer-details" }
