[package]
name = "plateau"
description = "A low-profile event and log aggregator"
license = "MIT"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "*"
log = "0.4"
openssl = { version = "*", features = ["vendored"] }
parquet = "5.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.5.9", features = [ "chrono", "sqlite", "runtime-tokio-native-tls" ] }
warp = "0.3"

[dev-dependencies]
itermore = "0.1"