[package]
name = "plateau"
description = "A low-profile event and log aggregator"
license = "MIT"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
futures = "*"
log = "0.4"
metrics = "0.16"
metrics-exporter-prometheus = "0.5"
thiserror = "1"

openssl = { version = "*", features = ["vendored"] }
parquet = "6.4"
pretty_env_logger = "0.4"
rweb = { version = "0.15", features = ["openapi"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"
tokio-stream = { version = "0.1.8", features = ["signal"] }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.5.9", features = [ "chrono", "sqlite", "runtime-tokio-native-tls" ] }

[dev-dependencies]
itermore = "0.1"