allow-branch = ["main", "release"]
push = true
tag = true
publish = false
verify = true
pre-release-commit-message = "Bump version to {{version}}"
tag-message = "v{{version}}"
tag-name = "v{{version}}"
