[package]
name = "plateau"
description = "A low-profile event and log aggregator"
authors = ["Wallaroo Labs"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[features]
test = []

[dependencies]
anyhow = "1"
bytesize = { version = "1.1.0", features = ["serde"] }
config = "0.13"
futures = "0.3"
itertools = "0.10"
log = "0.4"
metrics = "0.16"
metrics-exporter-prometheus = "0.5"
thiserror = "1"
parquet2 = { version = "0.17", default_features = false }
parquet-format-safe = "0.2"
plateau-client = { path = "../client", features = ["replicate"] }
plateau-transport = { path = "../transport" }
bytes = "1"
pretty_env_logger = "0.4"
humantime-serde = "1"
rweb = { version = "0.15", features = ["openapi"] }
serde_json = "1"
serde_qs = { version = "0.10", features = ["warp"] }
serde = { version = "1", features = ["derive"] }
tempfile = "3"
toml = "0.7"
tracing = "0.1"
tokio-stream = { version = "0.1", features = ["signal"] }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.5", features = [
  "chrono",
  "sqlite",
  "runtime-tokio-rustls",
] }
systemstat = "0.2"
rand = "0.8"
uuid = "1.4"

[dev-dependencies]
itermore = "0.1"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
uuid = { version = "1", features = ["v4", "fast-rng"] }
sample-test = "0.1"
sample-std = "0.1"
sample-arrow2 = "0.17"

[build-dependencies]
chrono = "0.4"

