[package]
name = "plateau-transport"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
rweb = "0.15"
structopt = { version = "0.3", optional = true }
arrow2 = { git = "https://github.com/WallarooLabs/arrow2", branch = "wallaroo/main", features = [
    "compute_aggregate",
    "compute_cast",
    "compute_comparison",
    "compute_concatenate",
    "compute_filter",
    "io_parquet",
    "io_ipc",
    "io_ipc_read_async",
    "io_json",
    "io_flight",
] }
chrono = "0.4"

[features]
structopt-cli = ["dep:structopt"]
