name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Announce Rust
      shell: bash
      run: cargo --version && rustc --version && rustup --version
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "20240509"
    - name: Check formatting
      shell: bash
      run: make check-fmt
    - name: Lint
      shell: bash
      run: make lint
    - name: Run tests
      shell: bash
      run: make test
